import type { Metadata } from "next";
import AuthSession from "./_component/AuthSession";
import { classNames } from "@/lib/uitls";
import { NanumGothic } from "@/lib/fonts";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import "swiper/css";
import "./globals.css";
import "github-markdown-css/github-markdown.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover"
        />
      </head>
      <body className={classNames(NanumGothic.className)}>
        <AuthSession>{children}</AuthSession>
        <ToastContainer />
      </body>
    </html>
  );
}
