import type { Metadata } from "next";
import AuthSession from "./_component/AuthSession";
import { classNames } from "@/lib/uitls";
import { NanumGothic } from "@/lib/fonts";
import { ToastContainer } from "react-toastify";

import "dayjs/locale/ko";

import "react-toastify/dist/ReactToastify.css";
import "swiper/css";
import "./globals.css";
import "github-markdown-css/github-markdown.css";

// notion 테마 스타일링 (필수)
import "react-notion-x/src/styles.css";

// 코드 하이라이트 스타일용
import "prismjs/themes/prism-tomorrow.css";
// 공식등 수학적 기호 스타일용
import "katex/dist/katex.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0, viewport-fit=cover, maximum-scale=1.0"
        />
      </head>
      <body className={classNames(NanumGothic.className)}>
        <AuthSession>
          {children}
          {modal}
        </AuthSession>
        <ToastContainer />
      </body>
    </html>
  );
}
